sudo: required
services:
  - docker

before_install:
  - docker build -t lillejohs/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lillejohs/react-test npm test

after_success:
  - docker build -t lillejohs/multi-client ./client
  - docker build -t lillejohs/multi-nginx ./nginx
  - docker build -t lillejohs/multi-server ./server
  - docker build -t lillejohs/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push lillejohs/multi-client
  - docker push lillejohs/multi-nginx
  - docker push lillejohs/multi-server
  - docker push lillejohs/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-1-601331528758
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id:
      secure: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY